name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # This will trigger the action when pushing to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build --source ./ --destination ./_site

      - name: Clear GitHub Actions cache (optional)
        run: git config --global --add safe.directory /github/workspace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.RESTAURANT_TOKEN }}  # Use your PAT secret here (GH_TOKEN) or use GITHUB_TOKEN
          publish_dir: ./_site
          target_branch: main

      - name: Commit and push changes (optional)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy built site to main branch"
          git push origin main
