name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --verbose

      - name: Build site
        run: bundle exec jekyll build --source ./ --destination ./_site --verbose

      - name: Clear GitHub Actions cache (if needed)
        run: git config --global --add safe.directory /github/workspace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Make sure this is configured correctly
          publish_dir: ./_site
